# =========================================================================== #
# 
#
# make                  Copy the files [01-99]-*/pdf/* into All/
#                       The directory 00-Template is ignored.
# 
# make example          Create an example directory
#                       which you can descend into and issue make.
#
# make clean            Remove the example directory and clean
#                       the subdirectories.
#
# make veryclean        Clean and remove the pdf in All/.
#
# make recursive        Descend into each subdirectory, build everything,
#                       and gather the pdf.
#
# 
# =========================================================================== #
#
#
include ../Common/subdir.mk
