#
#    make           Copy the files [01-99]-*/pdf/* into All/
#                   The directory 00-Template is ignored.
# 
#    make example   Create an example directory
#                   which you can descend into and issue make.
#
#    make clean     Remove files in All/
#                   and remove the example directory.
#
#
include ../Common/subdir.mk
