# =========================================================================== #
# 
#
# make                  Copy the files [01-99]-*/pdf/* into All/
#                       The directory 00-Template is ignored.
# 
# make new=99-Dirname   Create a new directory called 99-Dirname
#                       and sync 00-Template into it.
#
# make recursive        Descend into each directory, build everything,
#                       and gather the pdf.
#
# make clean            Clean the directories.
#
# make veryclean        Clean the directories and remove the pdf in All/.
#
# 
# =========================================================================== #
#
#
include ../Common/subdir.mk
