#
#    make               Compile the file main.tex
#                       and place the resulting file in pdf/.
# 
#    make bib           Run the latex bibliography engine
#                       and recompile the latex file.
#
#    make corrige       Append -corrige to the pdf name.
#
#    make addendum      Append -addendum to the pdf name.
# 
#    make clean         Remove files in out/
#
#    make veryclean     Remove files in out/ and pdf/
#
#
include ../info.mk
include ../../Common/info.mk
include ../../Common/common_subsubdir.mk
include ../../Common/common.mk
